# Generated by Django 5.0.2 on 2024-02-25 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0003_chatroom_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
