# Generated by Django 5.0.2 on 2024-02-22 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='coursestudent',
            name='text_feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
