# Generated by Django 5.0.2 on 2024-02-22 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_rename_course_name_course_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='section',
            old_name='title',
            new_name='name',
        ),
    ]
