# Generated by Django 5.0.2 on 2024-02-22 07:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_rename_title_section_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='videoelement',
            old_name='url',
            new_name='content',
        ),
        migrations.AddField(
            model_name='textelement',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='videoelement',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='section',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='textelement',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_elements', to='courses.section'),
        ),
        migrations.AlterField(
            model_name='videoelement',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_elements', to='courses.section'),
        ),
    ]
